name: dawini
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_screenutil: ^5.9.3
  flutter_localization: ^0.3.2
  dots_indicator: ^4.0.1
  pinput: ^5.0.1
  smooth_page_indicator: ^1.2.1
  page_transition: ^2.2.1
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  board_datetime_picker: ^2.8.0
  awesome_snackbar_content: ^0.1.6
  flutter_switch: ^0.3.2
  supabase_flutter: ^2.9.1
  shimmer: ^3.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hospitals/
    - assets/font/
    - assets/lang/
    - assets/icons/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/font/Cairo-SemiBold.ttf
        - asset: assets/font/Cairo-Bold.ttf
          weight: 700

    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins-Bold.ttf
